### ISSUE TITLE
이론 보완 형식

### ISSUE THREAD

**Issue by LEEHYUNDONG** [CS-studi/CS-study#2]
## 파일 위치(ex. CS/Network/oauth.md)

보완 내용

**Comment by guswns3371** [comment]
참고하면 좋을것 같아서 올립니다!

- [공식문서](https://oauth.net/articles/authentication/)
- [ID token 과 Access Token 차이점](https://auth0.com/blog/id-token-access-token-what-is-the-difference/)
- [What is OpenId Connect](https://nordicapis.com/what-is-openid-connect/)
- [Google - OIDC문서](https://developers.google.com/identity/protocols/oauth2/openid-connect)
  - Google, Line만 공식적인 OIDC Provider이다 (Naver, Facebook, Kakao 는 아님) ([참고](https://openid.net/certification/))

**Comment by LEEHYUNDONG** [comment]
#### Netwok/OAuth/이현동
#### CS/Network/OAuth

일요일까지 올리겠습니당!
