### ISSUE TITLE
db clustering 질문

### ISSUE THREAD

**Issue by LEEHYUNDONG** [CS-studi/CS-study#3]
### Clustering

@guswns3371 

db clustering에서 예시 사진(https://github.com/CS-studi/CS-study/blob/master/CS/Database/img/ClusteringReplicationShardingPartitioning/Untitled%201.png)은 하나의 데이터베이스를 여러대 서버가 공유하는 것처럼 나와있는데 데이터의 중복 아래 내용 설명부분에 "여러대의 서버에 데이터베이스를 중복저장한다" => 이부분은 replication이 적용된 clustering이 이난가 해서요.

답변주시면 감사하겠습니다.

**Comment by guswns3371** [comment]
```
Clustering의 장점

데이터 중복

클러스터링 기법에서 “데이터 중복”은 여러 데이터베이스 서버 사이의 데이터 동기화를 위해 일어난다. 동일한 데이터를 여러 서버에 중복 저장하므로써 하나의 서버가 고장나더라도 다른 서버를 통해 데이터를 제공할 수 있다.

로드 밸런싱

여러 데이터베이스 서버로 부하를 분산시켜 사용자의 요청을 더 많이 수용할 수 있다.

높은 가용성

여러 대의 데이터베이스 서버를 가지므로 높은 가용성을 보장한다.
```
에서 "동일한 데이터를 여러 서버에 중복 저장"한다는 부분이
"replication이 적용된 clustering"의 장점을 설명한거였습니다.

제가 애매하게 적었네요. 수정해서 다시 올릴께요!

**Comment by LEEHYUNDONG** [comment]
넵 피드백 감사합니다 내일봅시다!🙏
